language: generic
os:
- linux
- osx
env:
  matrix:
  - PYTHON="3.6"
  - PYTHON="3.7"
  - PYTHON="3.8"
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > $HOME/miniconda.sh
  else
    curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > $HOME/miniconda.sh
  fi
- bash $HOME/miniconda.sh -b -p $HOME/anaconda
- export PATH="$HOME/anaconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda env create -n test_env python=$PYTHON
- source activate test_env
- conda info -a && conda list
install:
- conda install landlab -c conda-forge
- pip install -e .
- pip install -r requirements-testing.txt
script:
- pytest --cov=sequence --cov-report= --cov-report=xml -vvv
- make lint install
- sequence run data/marmara/marmara.yaml
after_success:
- coveralls --verbose
