language: generic
os:
- linux
- osx
env:
  matrix:
  - CONDA_ENV=py36
  - CONDA_ENV=py37
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > $HOME/miniconda.sh
  else
    curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > $HOME/miniconda.sh
  fi
- bash $HOME/miniconda.sh -b -p $HOME/anaconda
- export PATH="$HOME/anaconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda env create -n test_env --file ci/requirements-$CONDA_ENV.yml
- source activate test_env
script:
- pytest --cov=sequence --cov-report= --cov-report=xml -vvv
- make lint install
- cd data/marmara && sequence marmara.yaml
after_success:
- coveralls --verbose
